version: '2'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - .:/usr/src/app
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - HTTP_PORT=4000
      - MONGODB_URI=mongodb://mongodb:27017/db-patients
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./databases:/data/db

  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm test
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=test
      - HTTP_PORT=4000
